ideacrew/edi_gateway

- .github/workflows/.build_image.yml
- app/operations/tax1095a/transformers/insurance_policies/cv3_family.rb
[IVL-184450326](https://www.pivotaltracker.com/n/projects/2481183/stories/184450326)
> handle tax household members split between months scenario

- Gemfile.lock
- app/event_source/events/insurance_policies/posted.rb
- app/event_source/publishers/insurance_policies/posted_publisher.rb
[IVL-184380968](https://www.pivotaltracker.com/n/projects/2481183/stories/184380968)
> publisher and event for event edi_gateway.insurance_policies.posted

- app/operations/insurance_policies/aca_individuals/insurance_policies/construct_cv3_payload.rb
- app/operations/insurance_policies/send_family_payload.rb
- app/operations/tax1095a/transformers/insurance_policies/cv3_family.rb
[ME-184544452](https://www.pivotaltracker.com/story/show/184544452)
> fix cv3 family payload generation issues

- app/event_source/subscribers/insurance_policies/tax1095a_payload_requested_subscriber.rb
[ME-184544452](https://www.pivotaltracker.com/story/show/184544452)
> fix namespace issue with subscriber

- app/models/data_stores/contract_holder_sync_job.rb
- script/clone_subjects_from_sync_job.rb
- script/contact_holder_sync_job_actions.rb
[ME-184585904](https://www.pivotaltracker.com/story/show/184585904)
> added scripts needed to process failed subjects

- app/operations/data_stores/contract_holder_sync_jobs/create.rb
- app/operations/insurance_policies/glue_policy_query.rb
- app/operations/insurance_policies/refresh.rb
- spec/operations/insurance_policies/refresh_spec.rb
[ME-184587520](https://www.pivotaltracker.com/story/show/184587520)
> update refresh operation to accept inclusion list of policies

- Gemfile.lock
- app/models/insurance_policies/aca_individuals/tax_household.rb
- app/operations/insurance_policies/aca_individuals/insurance_policies/construct_cv3_payload.rb
- spec/test_payloads/sample_cv3_family_policies.json
https://www.pivotaltracker.com/n/projects/2481183/stories/184608860
> pass primary_tax_filer_hbx_id in cv3_payload from edi to fdsh gateway

- app/models/insurance_policies/aca_individuals/tax_household.rb
- spec/factories/insurance_policies/aca_individuals/tax_household_members.rb
- spec/models/insurance_policies/aca_individuals/tax_household_spec.rb
- spec/models/people/person_spec.rb
https://www.pivotaltracker.com/n/projects/2481183/stories/184700853
> Correctly Pick Tax_Filer in a THH when multiple tax_filers are present in a household

- app/operations/insurance_policies/aca_individuals/insurance_policies/construct_cv3_payload.rb
- app/operations/insurance_policies/aca_individuals/irs_groups/construct_cv3_payload.rb
- spec/operations/insurance_policies/aca_individuals/irs_groups/construct_cv3_payload_spec.rb
[IVL-184589584](https://www.pivotaltracker.com/n/projects/2481183/stories/184589584)
> remove policy event filter for event insurance_policies.posted

- Gemfile.lock
- app/models/insurance_policies/insurance_product.rb
- app/operations/irs_groups/calculate_dental_premium_for_enrolled_children.rb
- app/operations/irs_groups/create_or_update_enrollments_for_policies.rb
- spec/operations/irs_groups/calculate_dental_premium_for_enrolled_children_spec.rb
[ME-184696691](https://www.pivotaltracker.com/n/projects/2502930/stories/184696691)
> popualte primary_enrollee_two_dependent for insurance product

- app/models/insurance_policies/aca_individuals/tax_household.rb
- spec/models/insurance_policies/aca_individuals/insurance_policy_spec.rb
- spec/models/insurance_policies/aca_individuals/tax_household_spec.rb
https://www.pivotaltracker.com/n/projects/2502930/stories/184824162
> Pull non_filer member as primary if no tax_filers are present in a tax_household

- app/operations/insurance_policies/aca_individuals/insurance_policies/construct_cv3_payload.rb
- spec/operations/insurance_policies/aca_individuals/insurance_policies/construct_cv3_payload_spec.rb
https://www.pivotaltracker.com/n/projects/2502930/stories/184826747
> pick only aqhp enr_thhs if tax_household is aqhp

- app/operations/insurance_policies/aca_individuals/insurance_policies/construct_cv3_payload.rb
- spec/factories/insurance_policies/aca_individuals/enrollments_and_tax_households.rb
- spec/operations/insurance_policies/aca_individuals/insurance_policies/construct_cv3_payload_spec.rb
https://www.pivotaltracker.com/n/projects/2502930/stories/184840489
> Fix coverage dates issue v2

- app/models/insurance_policies/aca_individuals/insurance_policy.rb
- app/operations/insurance_policies/aca_individuals/insurance_policies/construct_cv3_payload.rb
- app/operations/irs_groups/calculate_dental_premium_for_enrolled_children.rb
- app/operations/irs_groups/create_or_update_tax_households_and_groups.rb
- spec/models/insurance_policies/aca_individuals/insurance_policy_spec.rb
- spec/operations/insurance_policies/aca_individuals/insurance_policies/construct_cv3_payload_spec.rb
https://www.pivotaltracker.com/n/projects/2502930/stories/184849333
> Fix Mid Year Tax change APTC allocation issue

- app/operations/insurance_policies/aca_individuals/insurance_policies/construct_cv3_payload.rb
https://www.pivotaltracker.com/n/projects/2502930/stories/184850849
> Fix UQHP 0 premium issue

- app/models/data_stores/contract_holder_subject.rb
- spec/factories/data_stores/contract_holder_sync_jobs.rb
- spec/models/data_stores/contract_holder_subject_spec.rb
- spec/operations/data_stores/contract_holder_subjects/create_or_update_spec.rb
- spec/operations/data_stores/contract_holder_sync_jobs/process_response_event_spec.rb
- spec/operations/insurance_policies/contract_holders/create_or_update_spec.rb
- spec/operations/insurance_policies/send_family_payload_spec.rb
[ME-184850881](https://www.pivotaltracker.com/n/projects/2502930/stories/184850881)
> add to subject's policies instead of replacing them

- app/operations/irs_groups/create_or_update_enrollments_tax_households.rb
- spec/operations/irs_groups/create_or_update_enrollments_tax_households_spec.rb
https://www.pivotaltracker.com/n/projects/2502930/stories/184858307
> Update Benchmark and APTC premiums on Enrollment Tax Households

- app/models/insurance_policies/aca_individuals/enrollment.rb
- spec/models/insurance_policies/aca_individuals/enrollment_spec.rb
[ME-184951642](https://www.pivotaltracker.com/n/projects/2502930/stories/184951642/)
> pediatric dental adjustment applies for all covered members irrespective of member determination

- Gemfile.lock
- app/event_source/subscribers/insurance_policies/tax1095a_payload_requested_subscriber.rb
https://www.pivotaltracker.com/n/projects/2502930/stories/184933632
> additional logging

- app/models/insurance_policies/aca_individuals/insurance_policy.rb
- app/operations/insurance_policies/aca_individuals/insurance_policies/construct_cv3_payload.rb
- spec/models/insurance_policies/aca_individuals/insurance_policy_spec.rb
https://www.pivotaltracker.com/n/projects/2502930/stories/184839117
> Do not populate SLCSP if APTC is 0

- app/models/data_stores/contract_holder_sync_job.rb
- spec/models/data_stores/contract_holder_sync_job_spec.rb
[ME-185002741](https://www.pivotaltracker.com/story/show/185002741)
> fix timespan validation issues and add specs

- app/event_source/subscribers/families/found_by_subscriber.rb
- app/operations/data_stores/contract_holder_sync_jobs/process_response_event.rb
- spec/operations/data_stores/contract_holder_sync_jobs/process_response_event_spec.rb
[IVL-185025869](https://www.pivotaltracker.com/n/projects/2481183/stories/185025869)
> add CV3 family error messages to contract holder subject

- app/operations/reports/generate_pre_audit_report.rb
- spec/operations/reports/generate_pre_audit_report_spec.rb
[IVL-185250246](https://www.pivotaltracker.com/n/projects/2481183/stories/185250246)
> Generating the Pre-audit files with the file naming convention

- app/operations/reports/generate_pre_audit_report.rb
[IVL-185194325](https://www.pivotaltracker.com/story/show/185194325)
> Pre-Audit extract date and time

- app/operations/reports/generate_rcno_report.rb
[IVL-185194406](https://www.pivotaltracker.com/story/show/185194406)
> RCNO segment start date mismatch is overall N (non-match), not R (issuer leftover)

- app/operations/reports/generate_rcno_report.rb
[IVL-185151403](https://www.pivotaltracker.com/n/projects/2481183/stories/185151403)
[IVL-185151402](https://www.pivotaltracker.com/story/show/185151402)
[IVL-185151338](https://www.pivotaltracker.com/story/show/185151338)
> Field level matching for mailing, residential address, residential county and rating area codes

- app/operations/insurance_policies/aca_individuals/insurance_policies/construct_cv3_payload.rb
- spec/operations/insurance_policies/aca_individuals/insurance_policies/construct_cv3_payload_spec.rb
[ME-185510131](https://www.pivotaltracker.com/story/show/185510131)
> Incorrect date issue on 1095 document

- app/models/ard_segment.rb
- app/models/audit_report_datum.rb
- app/models/generators/coverage_information_serializer.rb
- app/operations/reports/generate_pre_audit_report.rb
- app/operations/reports/generate_rcno_report.rb
- app/operations/reports/request_coverage_history_for_subscriber.rb
- spec/operations/reports/generate_pre_audit_report_spec.rb
- spec/operations/reports/generate_rcno_report_spec.rb
- spec/operations/reports/request_coverage_history_for_subsriber_spec.rb
[IVL-5120297](https://www.pivotaltracker.com/epic/show/5120297)
[IVL-185194364](https://www.pivotaltracker.com/story/show/185194364)
[IVL-185194362](https://www.pivotaltracker.com/story/show/185194362)
> segment-level dispositioning of SBM leftover records with disposition of 'G'

- app/operations/reports/generate_rcno_report.rb
- script/rcno_metric_report.rb
https://www.pivotaltracker.com/n/projects/2502930/stories/185864044
Adding additional fields to RCNO metrics output that were previously added to the RCNO
> adding additional fields to RCNO metrics output for hios issuer

- app/operations/reports/generate_rcno_report.rb
[iVL-185875186](https://www.pivotaltracker.com/story/show/185875186)
> refactoring the code to fix overall flag

- app/operations/reports/generate_pre_audit_report.rb
https://www.pivotaltracker.com/n/projects/2502930/stories/185942404
Calling function for tra start and end dates that returns nil if the enrollee is not the subscriber
> removing tra dates for non subscribers in pre audit

- app/operations/reports/generate_rcno_report.rb
(https://www.pivotaltracker.com/story/show/186350822)
As per client's request, reverting recent change for canceled policy check
> reverting changes for canceled policies

- app/models/insurance_policies/aca_individuals/enrollment.rb
- app/operations/insurance_policies/aca_individuals/insurance_policies/construct_cv3_payload.rb
- spec/models/insurance_policies/aca_individuals/enrollment_spec.rb
https://www.pivotaltracker.com/story/show/186647918
> fix flipping of coverage dates for mid-year dependent add/drop

- app/models/insurance_policies/aca_individuals/insurance_policy.rb
- spec/models/insurance_policies/aca_individuals/insurance_policy_spec.rb
https://www.pivotaltracker.com/story/show/186702869
> fetches enrollments that are effective on last day of the month

- app/operations/insurance_policies/aca_individuals/insurance_policies/construct_cv3_payload.rb
- spec/operations/insurance_policies/aca_individuals/insurance_policies/construct_cv3_payload_spec.rb
https://www.pivotaltracker.com/story/show/186728526
> fetch valid enrolled tax household members from enrollments_tax_households

- app/models/insurance_policies/aca_individuals/enrollment.rb
- app/operations/insurance_policies/aca_individuals/insurance_policies/calculate_total_premium.rb
- app/operations/insurance_policies/aca_individuals/insurance_policies/construct_cv3_payload.rb
- app/operations/irs_groups/calculate_dental_premium_for_enrolled_children.rb
- spec/models/insurance_policies/aca_individuals/enrollment_spec.rb
- spec/operations/insurance_policies/aca_individuals/insurance_policies/calculate_total_premium_spec.rb
- spec/operations/irs_groups/calculate_dental_premium_for_enrolled_children_spec.rb
https://www.pivotaltracker.com/story/show/186714518
> calculate pro-rated premium for pediatric dental coverage

- Gemfile.lock
[pivotal-186740508](https://www.pivotaltracker.com/story/show/186740508)
> update event_source gem reference

- spec/operations/tax1095a/transformers/insurance_policies/cv3_family_spec.rb
[pivotal-186774080](https://www.pivotaltracker.com/story/show/186774080)
> spec fix 1_3_24

- Gemfile
- Gemfile.lock
- config/development.yml
- config/development/rabbitmq_config.yml
- config/initializers/event_source.rb
**Reference Ticket:** [pivotal-186813463](https://www.pivotaltracker.com/story/show/186813463)
**Current Branch Status:**
**Trunk Branch Status:**
**Summary:**
**For config/development/rabbitmq_config.yml:**
```
- Added a new configuration file `rabbitmq_config.yml` under the development config directory.
- This file contains the default configuration for RabbitMQ, including username, password, URL, port, vhost, and host.
- Since these values are suitable for the development environment, moved them to development folder.
```
**For config/initializers/event_source.rb:**
```
- Updated the `event_source.rb` initializer to use the configuration values from `rabbitmq_config.yml`.
- This change allows us to manage RabbitMQ development configurations in a centralized location.
```
**For …
> security vulnerability fix 1_9_24

- app/operations/tax1095a/publish_family_payload.rb
- spec/operations/tax1095a/publish_family_payload_spec.rb
Reference ticket: [pivotal-186373699](https://www.pivotaltracker.com/story/show/186373699)
> fetch tax_year from params

- Gemfile.lock
[Jolly Podgers Development - 187062137](https://www.pivotaltracker.com/story/show/187062137)
* Updates Aca Entities gem sha to the latest.
> updates aca_entities sha to the latest

- .github/workflows/security_checks.yml
- Gemfile
- Gemfile.lock
https://www.pivotaltracker.com/n/projects/2640060/stories/187151415
> upgrade yard gem

- app/operations/generators/reports/sbmi_xml_merger.rb
- spec/operations/generators/reports/sbmi_serializer_spec.rb
https://www.pivotaltracker.com/story/show/187090017
> update PBP filename structure based on cms eft serverless feature
